BEGIN;

-- Drop order
DROP TABLE IF EXISTS return_items;
DROP TABLE IF EXISTS returns;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS customers;

-- Enums
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
    CREATE TYPE order_status AS ENUM ('completed','cancelled');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_channel') THEN
    CREATE TYPE sales_channel AS ENUM ('web','app');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method') THEN
    CREATE TYPE payment_method AS ENUM ('cod','card','wallet');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
    CREATE TYPE payment_status AS ENUM ('authorized','captured','failed','refunded');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'return_status') THEN
    CREATE TYPE return_status AS ENUM ('requested','approved','rejected','received','refunded');
  END IF;
END $$;

-- Customers
CREATE TABLE customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   TEXT NOT NULL,
  email       TEXT NOT NULL UNIQUE,
  city        TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Categories
CREATE TABLE categories (
  category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Products
CREATE TABLE products (
  product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id  BIGINT NOT NULL REFERENCES categories(category_id),
  sku          TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  unit_cost    NUMERIC(14,2) NOT NULL CHECK (unit_cost >= 0),
  list_price   NUMERIC(14,2) NOT NULL CHECK (list_price >= 0),
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Orders: store snapshot totals for analytics + finance
CREATE TABLE orders (
  order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  BIGINT NOT NULL REFERENCES customers(customer_id),

  order_date   TIMESTAMPTZ NOT NULL,
  status       order_status NOT NULL,
  channel      sales_channel NOT NULL,

  shipping_fee     NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
  items_subtotal   NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (items_subtotal >= 0),
  discount_total   NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
  order_total      NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (order_total >= 0),

  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Order items
CREATE TABLE order_items (
  order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
  product_id    BIGINT NOT NULL REFERENCES products(product_id),

  quantity      INT NOT NULL CHECK (quantity > 0),
  unit_price    NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
  discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT chk_discount_not_exceed_line
    CHECK (discount_amount <= (quantity * unit_price))
);

-- Payments
CREATE TABLE payments (
  payment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,

  method      payment_method NOT NULL,
  status      payment_status NOT NULL DEFAULT 'captured',

  paid_amount NUMERIC(14,2) NOT NULL CHECK (paid_amount >= 0),
  paid_at     TIMESTAMPTZ NOT NULL,

  provider_txn_id TEXT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Returns
CREATE TABLE returns (
  return_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      BIGINT NOT NULL UNIQUE REFERENCES orders(order_id) ON DELETE CASCADE,

  status        return_status NOT NULL DEFAULT 'requested',
  return_date   TIMESTAMPTZ NOT NULL,
  reason        TEXT NOT NULL,

  refund_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (refund_amount >= 0),

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE return_items (
  return_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id      BIGINT NOT NULL REFERENCES returns(return_id) ON DELETE CASCADE,
  order_item_id  BIGINT NOT NULL REFERENCES order_items(order_item_id),

  quantity       INT NOT NULL CHECK (quantity > 0),
  refund_amount  NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (refund_amount >= 0)
);

-- Rule: returns only for completed orders
CREATE OR REPLACE FUNCTION trg_returns_only_completed()
RETURNS trigger AS $$
DECLARE st order_status;
BEGIN
  SELECT status INTO st FROM orders WHERE order_id = NEW.order_id;
  IF st IS DISTINCT FROM 'completed' THEN
    RAISE EXCEPTION 'Returns allowed only for completed orders. order_id=% status=%', NEW.order_id, st;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER returns_only_completed
BEFORE INSERT OR UPDATE ON returns
FOR EACH ROW EXECUTE FUNCTION trg_returns_only_completed();

-- Indexes
CREATE INDEX idx_orders_date_status ON orders (order_date, status);
CREATE INDEX idx_orders_customer_date ON orders (customer_id, order_date);

CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);

CREATE INDEX idx_products_category ON products (category_id);

CREATE INDEX idx_payments_order_paidat ON payments (order_id, paid_at);
CREATE INDEX idx_returns_date ON returns (return_date);

COMMIT;




CREATE OR REPLACE VIEW v_order_net_revenue AS
SELECT
  o.order_id,
  o.customer_id,
  o.order_date,
  o.channel,
  o.status,
  COALESCE(p.paid_amount, 0) AS paid_amount,
  COALESCE(r.refund_amount, 0) AS refund_amount,
  (COALESCE(p.paid_amount, 0) - COALESCE(r.refund_amount, 0)) AS net_revenue
FROM orders o
LEFT JOIN payments p ON p.order_id = o.order_id AND p.status IN ('captured','authorized')
LEFT JOIN returns r ON r.order_id = o.order_id;